DROP SCHEMA `TEST`;

CREATE SCHEMA `TEST` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE TEST.USER (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

INSERT INTO `TEST`.`USER`
(`USER_NAME`)
VALUES
('Tabris');

INSERT INTO `TEST`.`USER`
(`USER_NAME`)
VALUES
('John');

INSERT INTO `TEST`.`USER`
(`USER_NAME`)
VALUES
('Alien');

INSERT INTO `TEST`.`USER`
(`USER_NAME`)
VALUES
('Ian');