package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpMapEmpRole generated by hbm2java
 */
@Entity
@Table(name = "UMDP_MAP_EMP_ROLE", catalog = "UMDP")
public class UmdpMapEmpRole implements java.io.Serializable {


  private UmdpMapEmpRoleId id;
  private Date startDate;
  private Date endDate;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpMapEmpRole() {}


  public UmdpMapEmpRole(UmdpMapEmpRoleId id) {
    this.id = id;
  }

  public UmdpMapEmpRole(UmdpMapEmpRoleId id, Date startDate, Date endDate, String createUser,
      Date createDate, String updateUser, Date updateDate) {
    this.id = id;
    this.startDate = startDate;
    this.endDate = endDate;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @EmbeddedId


  @AttributeOverrides({
      @AttributeOverride(name = "empId",
          column = @Column(name = "EMP_ID", nullable = false, length = 50)),
      @AttributeOverride(name = "roleCd",
          column = @Column(name = "ROLE_CD", nullable = false, length = 100))})
  public UmdpMapEmpRoleId getId() {
    return this.id;
  }

  public void setId(UmdpMapEmpRoleId id) {
    this.id = id;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "START_DATE", length = 26)
  public Date getStartDate() {
    return this.startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "END_DATE", length = 26)
  public Date getEndDate() {
    return this.endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


