package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCfgNotice generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CFG_NOTICE", catalog = "UMDP")
public class UmdpCfgNotice implements java.io.Serializable {


  private String noticeEventCd;
  private Boolean isEmail;
  private Boolean isSms;
  private String subject;
  private String content;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCfgNotice() {}


  public UmdpCfgNotice(String noticeEventCd) {
    this.noticeEventCd = noticeEventCd;
  }

  public UmdpCfgNotice(String noticeEventCd, Boolean isEmail, Boolean isSms, String subject,
      String content, String createUser, Date createDate, String updateUser, Date updateDate) {
    this.noticeEventCd = noticeEventCd;
    this.isEmail = isEmail;
    this.isSms = isSms;
    this.subject = subject;
    this.content = content;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "NOTICE_EVENT_CD", unique = true, nullable = false, length = 100)
  public String getNoticeEventCd() {
    return this.noticeEventCd;
  }

  public void setNoticeEventCd(String noticeEventCd) {
    this.noticeEventCd = noticeEventCd;
  }


  @Column(name = "IS_EMAIL")
  public Boolean getIsEmail() {
    return this.isEmail;
  }

  public void setIsEmail(Boolean isEmail) {
    this.isEmail = isEmail;
  }


  @Column(name = "IS_SMS")
  public Boolean getIsSms() {
    return this.isSms;
  }

  public void setIsSms(Boolean isSms) {
    this.isSms = isSms;
  }


  @Column(name = "SUBJECT", length = 200)
  public String getSubject() {
    return this.subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }


  @Column(name = "CONTENT", length = 1000)
  public String getContent() {
    return this.content;
  }

  public void setContent(String content) {
    this.content = content;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


