package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCfgMsg generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CFG_MSG", catalog = "UMDP")
public class UmdpCfgMsg implements java.io.Serializable {


  private UmdpCfgMsgId id;
  private String msg;
  private String msgDsc;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCfgMsg() {}


  public UmdpCfgMsg(UmdpCfgMsgId id) {
    this.id = id;
  }

  public UmdpCfgMsg(UmdpCfgMsgId id, String msg, String msgDsc, String createUser, Date createDate,
      String updateUser, Date updateDate) {
    this.id = id;
    this.msg = msg;
    this.msgDsc = msgDsc;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @EmbeddedId


  @AttributeOverrides({
      @AttributeOverride(name = "langCd",
          column = @Column(name = "LANG_CD", nullable = false, length = 100)),
      @AttributeOverride(name = "msgCd",
          column = @Column(name = "MSG_CD", nullable = false, length = 100))})
  public UmdpCfgMsgId getId() {
    return this.id;
  }

  public void setId(UmdpCfgMsgId id) {
    this.id = id;
  }


  @Column(name = "MSG", length = 1000)
  public String getMsg() {
    return this.msg;
  }

  public void setMsg(String msg) {
    this.msg = msg;
  }


  @Column(name = "MSG_DSC", length = 1000)
  public String getMsgDsc() {
    return this.msgDsc;
  }

  public void setMsgDsc(String msgDsc) {
    this.msgDsc = msgDsc;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


