package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCurSeq generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CUR_SEQ", catalog = "UMDP")
public class UmdpCurSeq implements java.io.Serializable {


  private String seqType;
  private String seq;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCurSeq() {}


  public UmdpCurSeq(String seqType) {
    this.seqType = seqType;
  }

  public UmdpCurSeq(String seqType, String seq, String createUser, Date createDate,
      String updateUser, Date updateDate) {
    this.seqType = seqType;
    this.seq = seq;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "SEQ_TYPE", unique = true, nullable = false, length = 50)
  public String getSeqType() {
    return this.seqType;
  }

  public void setSeqType(String seqType) {
    this.seqType = seqType;
  }


  @Column(name = "SEQ", length = 50)
  public String getSeq() {
    return this.seq;
  }

  public void setSeq(String seq) {
    this.seq = seq;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


