package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCfgDept generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CFG_DEPT", catalog = "UMDP")
public class UmdpCfgDept implements java.io.Serializable {


  private String id;
  private String deptChiName;
  private String deptEngName;
  private String deptSName;
  private String deptFullName;
  private Boolean isNt;
  private String costCenter;
  private Boolean isCostCenter;
  private String parentId;
  private Long depth;
  private Long seq;
  private Date setDate;
  private Date offDate;
  private String ownerId;
  private String deptLevel;
  private String deptLevelName;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCfgDept() {}


  public UmdpCfgDept(String id) {
    this.id = id;
  }

  public UmdpCfgDept(String id, String deptChiName, String deptEngName, String deptSName,
      String deptFullName, Boolean isNt, String costCenter, Boolean isCostCenter, String parentId,
      Long depth, Long seq, Date setDate, Date offDate, String ownerId, String deptLevel,
      String deptLevelName, String createUser, Date createDate, String updateUser,
      Date updateDate) {
    this.id = id;
    this.deptChiName = deptChiName;
    this.deptEngName = deptEngName;
    this.deptSName = deptSName;
    this.deptFullName = deptFullName;
    this.isNt = isNt;
    this.costCenter = costCenter;
    this.isCostCenter = isCostCenter;
    this.parentId = parentId;
    this.depth = depth;
    this.seq = seq;
    this.setDate = setDate;
    this.offDate = offDate;
    this.ownerId = ownerId;
    this.deptLevel = deptLevel;
    this.deptLevelName = deptLevelName;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false, length = 100)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Column(name = "DEPT_CHI_NAME", length = 200)
  public String getDeptChiName() {
    return this.deptChiName;
  }

  public void setDeptChiName(String deptChiName) {
    this.deptChiName = deptChiName;
  }


  @Column(name = "DEPT_ENG_NAME", length = 200)
  public String getDeptEngName() {
    return this.deptEngName;
  }

  public void setDeptEngName(String deptEngName) {
    this.deptEngName = deptEngName;
  }


  @Column(name = "DEPT_S_NAME", length = 200)
  public String getDeptSName() {
    return this.deptSName;
  }

  public void setDeptSName(String deptSName) {
    this.deptSName = deptSName;
  }


  @Column(name = "DEPT_FULL_NAME")
  public String getDeptFullName() {
    return this.deptFullName;
  }

  public void setDeptFullName(String deptFullName) {
    this.deptFullName = deptFullName;
  }


  @Column(name = "IS_NT")
  public Boolean getIsNt() {
    return this.isNt;
  }

  public void setIsNt(Boolean isNt) {
    this.isNt = isNt;
  }


  @Column(name = "COST_CENTER", length = 100)
  public String getCostCenter() {
    return this.costCenter;
  }

  public void setCostCenter(String costCenter) {
    this.costCenter = costCenter;
  }


  @Column(name = "IS_COST_CENTER")
  public Boolean getIsCostCenter() {
    return this.isCostCenter;
  }

  public void setIsCostCenter(Boolean isCostCenter) {
    this.isCostCenter = isCostCenter;
  }


  @Column(name = "PARENT_ID", length = 100)
  public String getParentId() {
    return this.parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  @Column(name = "DEPTH")
  public Long getDepth() {
    return this.depth;
  }

  public void setDepth(Long depth) {
    this.depth = depth;
  }


  @Column(name = "SEQ")
  public Long getSeq() {
    return this.seq;
  }

  public void setSeq(Long seq) {
    this.seq = seq;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "SET_DATE", length = 26)
  public Date getSetDate() {
    return this.setDate;
  }

  public void setSetDate(Date setDate) {
    this.setDate = setDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "OFF_DATE", length = 26)
  public Date getOffDate() {
    return this.offDate;
  }

  public void setOffDate(Date offDate) {
    this.offDate = offDate;
  }


  @Column(name = "OWNER_ID", length = 50)
  public String getOwnerId() {
    return this.ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  @Column(name = "DEPT_LEVEL", length = 50)
  public String getDeptLevel() {
    return this.deptLevel;
  }

  public void setDeptLevel(String deptLevel) {
    this.deptLevel = deptLevel;
  }


  @Column(name = "DEPT_LEVEL_NAME", length = 200)
  public String getDeptLevelName() {
    return this.deptLevelName;
  }

  public void setDeptLevelName(String deptLevelName) {
    this.deptLevelName = deptLevelName;
  }


  @Column(name = "CREATE_USER")
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


