package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UmdpCfgNoticeGrpId generated by hbm2java
 */
@Embeddable
public class UmdpCfgNoticeGrpId implements java.io.Serializable {


  private String noticeGrpCd;
  private String empId;

  public UmdpCfgNoticeGrpId() {}

  public UmdpCfgNoticeGrpId(String noticeGrpCd, String empId) {
    this.noticeGrpCd = noticeGrpCd;
    this.empId = empId;
  }



  @Column(name = "NOTICE_GRP_CD", nullable = false, length = 100)
  public String getNoticeGrpCd() {
    return this.noticeGrpCd;
  }

  public void setNoticeGrpCd(String noticeGrpCd) {
    this.noticeGrpCd = noticeGrpCd;
  }


  @Column(name = "EMP_ID", nullable = false, length = 50)
  public String getEmpId() {
    return this.empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UmdpCfgNoticeGrpId))
      return false;
    UmdpCfgNoticeGrpId castOther = (UmdpCfgNoticeGrpId) other;

    return ((this.getNoticeGrpCd() == castOther.getNoticeGrpCd())
        || (this.getNoticeGrpCd() != null && castOther.getNoticeGrpCd() != null
            && this.getNoticeGrpCd().equals(castOther.getNoticeGrpCd())))
        && ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
            && castOther.getEmpId() != null && this.getEmpId().equals(castOther.getEmpId())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getNoticeGrpCd() == null ? 0 : this.getNoticeGrpCd().hashCode());
    result = 37 * result + (getEmpId() == null ? 0 : this.getEmpId().hashCode());
    return result;
  }


}


