package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpLogApi generated by hbm2java
 */
@Entity
@Table(name = "UMDP_LOG_API", catalog = "UMDP")
public class UmdpLogApi implements java.io.Serializable {


  private long id;
  private String sendSys;
  private String recvSys;
  private byte[] sendMsg;
  private byte[] recvMsg;
  private Date sendDate;
  private Date recvDate;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpLogApi() {}


  public UmdpLogApi(long id) {
    this.id = id;
  }

  public UmdpLogApi(long id, String sendSys, String recvSys, byte[] sendMsg, byte[] recvMsg,
      Date sendDate, Date recvDate, String createUser, Date createDate, String updateUser,
      Date updateDate) {
    this.id = id;
    this.sendSys = sendSys;
    this.recvSys = recvSys;
    this.sendMsg = sendMsg;
    this.recvMsg = recvMsg;
    this.sendDate = sendDate;
    this.recvDate = recvDate;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }


  @Column(name = "SEND_SYS", length = 100)
  public String getSendSys() {
    return this.sendSys;
  }

  public void setSendSys(String sendSys) {
    this.sendSys = sendSys;
  }


  @Column(name = "RECV_SYS", length = 100)
  public String getRecvSys() {
    return this.recvSys;
  }

  public void setRecvSys(String recvSys) {
    this.recvSys = recvSys;
  }


  @Column(name = "SEND_MSG")
  public byte[] getSendMsg() {
    return this.sendMsg;
  }

  public void setSendMsg(byte[] sendMsg) {
    this.sendMsg = sendMsg;
  }


  @Column(name = "RECV_MSG")
  public byte[] getRecvMsg() {
    return this.recvMsg;
  }

  public void setRecvMsg(byte[] recvMsg) {
    this.recvMsg = recvMsg;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "SEND_DATE", length = 10)
  public Date getSendDate() {
    return this.sendDate;
  }

  public void setSendDate(Date sendDate) {
    this.sendDate = sendDate;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "RECV_DATE", length = 10)
  public Date getRecvDate() {
    return this.recvDate;
  }

  public void setRecvDate(Date recvDate) {
    this.recvDate = recvDate;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


