package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpLogJob generated by hbm2java
 */
@Entity
@Table(name = "UMDP_LOG_JOB", catalog = "UMDP")
public class UmdpLogJob implements java.io.Serializable {


  private String id;
  private Long taskId;
  private String status;
  private Date executionTime;
  private byte[] exception;

  public UmdpLogJob() {}


  public UmdpLogJob(String id) {
    this.id = id;
  }

  public UmdpLogJob(String id, Long taskId, String status, Date executionTime, byte[] exception) {
    this.id = id;
    this.taskId = taskId;
    this.status = status;
    this.executionTime = executionTime;
    this.exception = exception;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false, length = 100)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Column(name = "TASK_ID")
  public Long getTaskId() {
    return this.taskId;
  }

  public void setTaskId(Long taskId) {
    this.taskId = taskId;
  }


  @Column(name = "STATUS", length = 1)
  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "EXECUTION_TIME", length = 26)
  public Date getExecutionTime() {
    return this.executionTime;
  }

  public void setExecutionTime(Date executionTime) {
    this.executionTime = executionTime;
  }


  @Column(name = "EXCEPTION")
  public byte[] getException() {
    return this.exception;
  }

  public void setException(byte[] exception) {
    this.exception = exception;
  }



}


