package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCurJob generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CUR_JOB", catalog = "UMDP")
public class UmdpCurJob implements java.io.Serializable {


  private long id;
  private String logId;
  private String type;
  private Date triggerTime;
  private Long cycle;
  private Long retryCount;
  private byte[] data;
  private String status;
  private Date executionTime;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCurJob() {}


  public UmdpCurJob(long id) {
    this.id = id;
  }

  public UmdpCurJob(long id, String logId, String type, Date triggerTime, Long cycle,
      Long retryCount, byte[] data, String status, Date executionTime, String createUser,
      Date createDate, String updateUser, Date updateDate) {
    this.id = id;
    this.logId = logId;
    this.type = type;
    this.triggerTime = triggerTime;
    this.cycle = cycle;
    this.retryCount = retryCount;
    this.data = data;
    this.status = status;
    this.executionTime = executionTime;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }


  @Column(name = "LOG_ID", length = 100)
  public String getLogId() {
    return this.logId;
  }

  public void setLogId(String logId) {
    this.logId = logId;
  }


  @Column(name = "TYPE", length = 100)
  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "TRIGGER_TIME", length = 26)
  public Date getTriggerTime() {
    return this.triggerTime;
  }

  public void setTriggerTime(Date triggerTime) {
    this.triggerTime = triggerTime;
  }


  @Column(name = "CYCLE")
  public Long getCycle() {
    return this.cycle;
  }

  public void setCycle(Long cycle) {
    this.cycle = cycle;
  }


  @Column(name = "RETRY_COUNT")
  public Long getRetryCount() {
    return this.retryCount;
  }

  public void setRetryCount(Long retryCount) {
    this.retryCount = retryCount;
  }


  @Column(name = "DATA")
  public byte[] getData() {
    return this.data;
  }

  public void setData(byte[] data) {
    this.data = data;
  }


  @Column(name = "STATUS", length = 1)
  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "EXECUTION_TIME", length = 26)
  public Date getExecutionTime() {
    return this.executionTime;
  }

  public void setExecutionTime(Date executionTime) {
    this.executionTime = executionTime;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


