package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCfgJob generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CFG_JOB", catalog = "UMDP")
public class UmdpCfgJob implements java.io.Serializable {


  private String type;
  private String className;
  private String cronTrigger;
  private Long retryLimit;
  private Boolean enabled;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCfgJob() {}


  public UmdpCfgJob(String type) {
    this.type = type;
  }

  public UmdpCfgJob(String type, String className, String cronTrigger, Long retryLimit,
      Boolean enabled, String createUser, Date createDate, String updateUser, Date updateDate) {
    this.type = type;
    this.className = className;
    this.cronTrigger = cronTrigger;
    this.retryLimit = retryLimit;
    this.enabled = enabled;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "TYPE", unique = true, nullable = false, length = 100)
  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Column(name = "CLASS_NAME", length = 200)
  public String getClassName() {
    return this.className;
  }

  public void setClassName(String className) {
    this.className = className;
  }


  @Column(name = "CRON_TRIGGER", length = 50)
  public String getCronTrigger() {
    return this.cronTrigger;
  }

  public void setCronTrigger(String cronTrigger) {
    this.cronTrigger = cronTrigger;
  }


  @Column(name = "RETRY_LIMIT")
  public Long getRetryLimit() {
    return this.retryLimit;
  }

  public void setRetryLimit(Long retryLimit) {
    this.retryLimit = retryLimit;
  }


  @Column(name = "ENABLED")
  public Boolean getEnabled() {
    return this.enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


