package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UmdpSyncEmpId generated by hbm2java
 */
@Embeddable
public class UmdpSyncEmpId implements java.io.Serializable {


  private Date syncDate;
  private String id;

  public UmdpSyncEmpId() {}

  public UmdpSyncEmpId(Date syncDate, String id) {
    this.syncDate = syncDate;
    this.id = id;
  }



  @Column(name = "SYNC_DATE", nullable = false, length = 26)
  public Date getSyncDate() {
    return this.syncDate;
  }

  public void setSyncDate(Date syncDate) {
    this.syncDate = syncDate;
  }


  @Column(name = "ID", nullable = false, length = 50)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UmdpSyncEmpId))
      return false;
    UmdpSyncEmpId castOther = (UmdpSyncEmpId) other;

    return ((this.getSyncDate() == castOther.getSyncDate()) || (this.getSyncDate() != null
        && castOther.getSyncDate() != null && this.getSyncDate().equals(castOther.getSyncDate())))
        && ((this.getId() == castOther.getId()) || (this.getId() != null
            && castOther.getId() != null && this.getId().equals(castOther.getId())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getSyncDate() == null ? 0 : this.getSyncDate().hashCode());
    result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
    return result;
  }


}


