package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UmdpCurEmpHabitId generated by hbm2java
 */
@Embeddable
public class UmdpCurEmpHabitId implements java.io.Serializable {


  private String empId;
  private String item;

  public UmdpCurEmpHabitId() {}

  public UmdpCurEmpHabitId(String empId, String item) {
    this.empId = empId;
    this.item = item;
  }



  @Column(name = "EMP_ID", nullable = false, length = 50)
  public String getEmpId() {
    return this.empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }


  @Column(name = "ITEM", nullable = false, length = 100)
  public String getItem() {
    return this.item;
  }

  public void setItem(String item) {
    this.item = item;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UmdpCurEmpHabitId))
      return false;
    UmdpCurEmpHabitId castOther = (UmdpCurEmpHabitId) other;

    return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
        && castOther.getEmpId() != null && this.getEmpId().equals(castOther.getEmpId())))
        && ((this.getItem() == castOther.getItem()) || (this.getItem() != null
            && castOther.getItem() != null && this.getItem().equals(castOther.getItem())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getEmpId() == null ? 0 : this.getEmpId().hashCode());
    result = 37 * result + (getItem() == null ? 0 : this.getItem().hashCode());
    return result;
  }


}


