package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UmdpCfgNoticeTargetId generated by hbm2java
 */
@Embeddable
public class UmdpCfgNoticeTargetId implements java.io.Serializable {


  private String noticeEventCd;
  private String noticeTarget;

  public UmdpCfgNoticeTargetId() {}

  public UmdpCfgNoticeTargetId(String noticeEventCd, String noticeTarget) {
    this.noticeEventCd = noticeEventCd;
    this.noticeTarget = noticeTarget;
  }



  @Column(name = "NOTICE_EVENT_CD", nullable = false, length = 100)
  public String getNoticeEventCd() {
    return this.noticeEventCd;
  }

  public void setNoticeEventCd(String noticeEventCd) {
    this.noticeEventCd = noticeEventCd;
  }


  @Column(name = "NOTICE_TARGET", nullable = false, length = 100)
  public String getNoticeTarget() {
    return this.noticeTarget;
  }

  public void setNoticeTarget(String noticeTarget) {
    this.noticeTarget = noticeTarget;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UmdpCfgNoticeTargetId))
      return false;
    UmdpCfgNoticeTargetId castOther = (UmdpCfgNoticeTargetId) other;

    return ((this.getNoticeEventCd() == castOther.getNoticeEventCd())
        || (this.getNoticeEventCd() != null && castOther.getNoticeEventCd() != null
            && this.getNoticeEventCd().equals(castOther.getNoticeEventCd())))
        && ((this.getNoticeTarget() == castOther.getNoticeTarget())
            || (this.getNoticeTarget() != null && castOther.getNoticeTarget() != null
                && this.getNoticeTarget().equals(castOther.getNoticeTarget())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getNoticeEventCd() == null ? 0 : this.getNoticeEventCd().hashCode());
    result = 37 * result + (getNoticeTarget() == null ? 0 : this.getNoticeTarget().hashCode());
    return result;
  }


}


