package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCfgParam generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CFG_PARAM", catalog = "UMDP")
public class UmdpCfgParam implements java.io.Serializable {


  private String code;
  private String codeName;
  private String codeValue;
  private String codeDsc;
  private Long seq;
  private String parentCd;
  private String sys;
  private String codeCate;
  private String cateName;
  private Boolean isEnable;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public UmdpCfgParam() {}


  public UmdpCfgParam(String code) {
    this.code = code;
  }

  public UmdpCfgParam(String code, String codeName, String codeValue, String codeDsc, Long seq,
      String parentCd, String sys, String codeCate, String cateName, Boolean isEnable,
      String createUser, Date createDate, String updateUser, Date updateDate) {
    this.code = code;
    this.codeName = codeName;
    this.codeValue = codeValue;
    this.codeDsc = codeDsc;
    this.seq = seq;
    this.parentCd = parentCd;
    this.sys = sys;
    this.codeCate = codeCate;
    this.cateName = cateName;
    this.isEnable = isEnable;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "CODE", unique = true, nullable = false, length = 100)
  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  @Column(name = "CODE_NAME", length = 200)
  public String getCodeName() {
    return this.codeName;
  }

  public void setCodeName(String codeName) {
    this.codeName = codeName;
  }


  @Column(name = "CODE_VALUE", length = 200)
  public String getCodeValue() {
    return this.codeValue;
  }

  public void setCodeValue(String codeValue) {
    this.codeValue = codeValue;
  }


  @Column(name = "CODE_DSC", length = 500)
  public String getCodeDsc() {
    return this.codeDsc;
  }

  public void setCodeDsc(String codeDsc) {
    this.codeDsc = codeDsc;
  }


  @Column(name = "SEQ")
  public Long getSeq() {
    return this.seq;
  }

  public void setSeq(Long seq) {
    this.seq = seq;
  }


  @Column(name = "PARENT_CD", length = 100)
  public String getParentCd() {
    return this.parentCd;
  }

  public void setParentCd(String parentCd) {
    this.parentCd = parentCd;
  }


  @Column(name = "SYS", length = 20)
  public String getSys() {
    return this.sys;
  }

  public void setSys(String sys) {
    this.sys = sys;
  }


  @Column(name = "CODE_CATE", length = 100)
  public String getCodeCate() {
    return this.codeCate;
  }

  public void setCodeCate(String codeCate) {
    this.codeCate = codeCate;
  }


  @Column(name = "CATE_NAME", length = 200)
  public String getCateName() {
    return this.cateName;
  }

  public void setCateName(String cateName) {
    this.cateName = cateName;
  }


  @Column(name = "IS_ENABLE")
  public Boolean getIsEnable() {
    return this.isEnable;
  }

  public void setIsEnable(Boolean isEnable) {
    this.isEnable = isEnable;
  }


  @Column(name = "CREATE_USER")
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


