package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UmdpCfgNoticeGrp generated by hbm2java
 */
@Entity
@Table(name = "UMDP_CFG_NOTICE_GRP", catalog = "UMDP")
public class UmdpCfgNoticeGrp implements java.io.Serializable {


  private UmdpCfgNoticeGrpId id;
  private String createUser;
  private Date createDate;

  public UmdpCfgNoticeGrp() {}


  public UmdpCfgNoticeGrp(UmdpCfgNoticeGrpId id) {
    this.id = id;
  }

  public UmdpCfgNoticeGrp(UmdpCfgNoticeGrpId id, String createUser, Date createDate) {
    this.id = id;
    this.createUser = createUser;
    this.createDate = createDate;
  }

  @EmbeddedId


  @AttributeOverrides({
      @AttributeOverride(name = "noticeGrpCd",
          column = @Column(name = "NOTICE_GRP_CD", nullable = false, length = 100)),
      @AttributeOverride(name = "empId",
          column = @Column(name = "EMP_ID", nullable = false, length = 50))})
  public UmdpCfgNoticeGrpId getId() {
    return this.id;
  }

  public void setId(UmdpCfgNoticeGrpId id) {
    this.id = id;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }



}


