package com.umdp.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UmdpMapEmpRoleId generated by hbm2java
 */
@Embeddable
public class UmdpMapEmpRoleId implements java.io.Serializable {


  private String empId;
  private String roleCd;

  public UmdpMapEmpRoleId() {}

  public UmdpMapEmpRoleId(String empId, String roleCd) {
    this.empId = empId;
    this.roleCd = roleCd;
  }



  @Column(name = "EMP_ID", nullable = false, length = 50)
  public String getEmpId() {
    return this.empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }


  @Column(name = "ROLE_CD", nullable = false, length = 100)
  public String getRoleCd() {
    return this.roleCd;
  }

  public void setRoleCd(String roleCd) {
    this.roleCd = roleCd;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UmdpMapEmpRoleId))
      return false;
    UmdpMapEmpRoleId castOther = (UmdpMapEmpRoleId) other;

    return ((this.getEmpId() == castOther.getEmpId()) || (this.getEmpId() != null
        && castOther.getEmpId() != null && this.getEmpId().equals(castOther.getEmpId())))
        && ((this.getRoleCd() == castOther.getRoleCd()) || (this.getRoleCd() != null
            && castOther.getRoleCd() != null && this.getRoleCd().equals(castOther.getRoleCd())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getEmpId() == null ? 0 : this.getEmpId().hashCode());
    result = 37 * result + (getRoleCd() == null ? 0 : this.getRoleCd().hashCode());
    return result;
  }


}


