package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurPirateIncident generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_PIRATE_INCIDENT", catalog = "UMDP")
public class FsmCurPirateIncident implements java.io.Serializable {


  private long id;
  private String latitude;
  private String longitude;
  private Date piDate;
  private String piSrcCd;
  private String vesselNo;
  private String summary;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurPirateIncident() {}


  public FsmCurPirateIncident(long id) {
    this.id = id;
  }

  public FsmCurPirateIncident(long id, String latitude, String longitude, Date piDate,
      String piSrcCd, String vesselNo, String summary, String createUser, Date createDate,
      String updateUser, Date updateDate) {
    this.id = id;
    this.latitude = latitude;
    this.longitude = longitude;
    this.piDate = piDate;
    this.piSrcCd = piSrcCd;
    this.vesselNo = vesselNo;
    this.summary = summary;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }


  @Column(name = "LATITUDE", length = 20)
  public String getLatitude() {
    return this.latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  @Column(name = "LONGITUDE", length = 20)
  public String getLongitude() {
    return this.longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "PI_DATE", length = 26)
  public Date getPiDate() {
    return this.piDate;
  }

  public void setPiDate(Date piDate) {
    this.piDate = piDate;
  }


  @Column(name = "PI_SRC_CD", length = 100)
  public String getPiSrcCd() {
    return this.piSrcCd;
  }

  public void setPiSrcCd(String piSrcCd) {
    this.piSrcCd = piSrcCd;
  }


  @Column(name = "VESSEL_NO", length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "SUMMARY", length = 2000)
  public String getSummary() {
    return this.summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


