package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FsmCurVesselNearbyId generated by hbm2java
 */
@Embeddable
public class FsmCurVesselNearbyId implements java.io.Serializable {


  private String thisVesselNo;
  private String mmsi;

  public FsmCurVesselNearbyId() {}

  public FsmCurVesselNearbyId(String thisVesselNo, String mmsi) {
    this.thisVesselNo = thisVesselNo;
    this.mmsi = mmsi;
  }



  @Column(name = "THIS_VESSEL_NO", nullable = false, length = 20)
  public String getThisVesselNo() {
    return this.thisVesselNo;
  }

  public void setThisVesselNo(String thisVesselNo) {
    this.thisVesselNo = thisVesselNo;
  }


  @Column(name = "MMSI", nullable = false, length = 20)
  public String getMmsi() {
    return this.mmsi;
  }

  public void setMmsi(String mmsi) {
    this.mmsi = mmsi;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof FsmCurVesselNearbyId))
      return false;
    FsmCurVesselNearbyId castOther = (FsmCurVesselNearbyId) other;

    return ((this.getThisVesselNo() == castOther.getThisVesselNo())
        || (this.getThisVesselNo() != null && castOther.getThisVesselNo() != null
            && this.getThisVesselNo().equals(castOther.getThisVesselNo())))
        && ((this.getMmsi() == castOther.getMmsi()) || (this.getMmsi() != null
            && castOther.getMmsi() != null && this.getMmsi().equals(castOther.getMmsi())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getThisVesselNo() == null ? 0 : this.getThisVesselNo().hashCode());
    result = 37 * result + (getMmsi() == null ? 0 : this.getMmsi().hashCode());
    return result;
  }


}


