package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurVesselAlarm generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_VESSEL_ALARM", catalog = "UMDP")
public class FsmCurVesselAlarm implements java.io.Serializable {


  private String vesselNo;
  private Long alarmCntPirateP;
  private Long alarmCntPirate;
  private Long alarmCntCollision;
  private Long alarmCntDamage;
  private Long alarmCntHeavyWeatherL4;
  private Long alarmCntHeavyWeatherL6;
  private Boolean isAlarmPirateP;
  private Boolean isAlarmPirate;
  private Boolean isAlarmCollision;
  private Boolean isAlarmDamage;
  private Boolean isAlarmHeavyWeatherL4;
  private Boolean isAlarmHeavyWeatherL6;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurVesselAlarm() {}


  public FsmCurVesselAlarm(String vesselNo) {
    this.vesselNo = vesselNo;
  }

  public FsmCurVesselAlarm(String vesselNo, Long alarmCntPirateP, Long alarmCntPirate,
      Long alarmCntCollision, Long alarmCntDamage, Long alarmCntHeavyWeatherL4,
      Long alarmCntHeavyWeatherL6, Boolean isAlarmPirateP, Boolean isAlarmPirate,
      Boolean isAlarmCollision, Boolean isAlarmDamage, Boolean isAlarmHeavyWeatherL4,
      Boolean isAlarmHeavyWeatherL6, String createUser, Date createDate, String updateUser,
      Date updateDate) {
    this.vesselNo = vesselNo;
    this.alarmCntPirateP = alarmCntPirateP;
    this.alarmCntPirate = alarmCntPirate;
    this.alarmCntCollision = alarmCntCollision;
    this.alarmCntDamage = alarmCntDamage;
    this.alarmCntHeavyWeatherL4 = alarmCntHeavyWeatherL4;
    this.alarmCntHeavyWeatherL6 = alarmCntHeavyWeatherL6;
    this.isAlarmPirateP = isAlarmPirateP;
    this.isAlarmPirate = isAlarmPirate;
    this.isAlarmCollision = isAlarmCollision;
    this.isAlarmDamage = isAlarmDamage;
    this.isAlarmHeavyWeatherL4 = isAlarmHeavyWeatherL4;
    this.isAlarmHeavyWeatherL6 = isAlarmHeavyWeatherL6;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "VESSEL_NO", unique = true, nullable = false, length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "ALARM_CNT_PIRATE_P")
  public Long getAlarmCntPirateP() {
    return this.alarmCntPirateP;
  }

  public void setAlarmCntPirateP(Long alarmCntPirateP) {
    this.alarmCntPirateP = alarmCntPirateP;
  }


  @Column(name = "ALARM_CNT_PIRATE")
  public Long getAlarmCntPirate() {
    return this.alarmCntPirate;
  }

  public void setAlarmCntPirate(Long alarmCntPirate) {
    this.alarmCntPirate = alarmCntPirate;
  }


  @Column(name = "ALARM_CNT_COLLISION")
  public Long getAlarmCntCollision() {
    return this.alarmCntCollision;
  }

  public void setAlarmCntCollision(Long alarmCntCollision) {
    this.alarmCntCollision = alarmCntCollision;
  }


  @Column(name = "ALARM_CNT_DAMAGE")
  public Long getAlarmCntDamage() {
    return this.alarmCntDamage;
  }

  public void setAlarmCntDamage(Long alarmCntDamage) {
    this.alarmCntDamage = alarmCntDamage;
  }


  @Column(name = "ALARM_CNT_HEAVY_WEATHER_L4")
  public Long getAlarmCntHeavyWeatherL4() {
    return this.alarmCntHeavyWeatherL4;
  }

  public void setAlarmCntHeavyWeatherL4(Long alarmCntHeavyWeatherL4) {
    this.alarmCntHeavyWeatherL4 = alarmCntHeavyWeatherL4;
  }


  @Column(name = "ALARM_CNT_HEAVY_WEATHER_L6")
  public Long getAlarmCntHeavyWeatherL6() {
    return this.alarmCntHeavyWeatherL6;
  }

  public void setAlarmCntHeavyWeatherL6(Long alarmCntHeavyWeatherL6) {
    this.alarmCntHeavyWeatherL6 = alarmCntHeavyWeatherL6;
  }


  @Column(name = "IS_ALARM_PIRATE_P")
  public Boolean getIsAlarmPirateP() {
    return this.isAlarmPirateP;
  }

  public void setIsAlarmPirateP(Boolean isAlarmPirateP) {
    this.isAlarmPirateP = isAlarmPirateP;
  }


  @Column(name = "IS_ALARM_PIRATE")
  public Boolean getIsAlarmPirate() {
    return this.isAlarmPirate;
  }

  public void setIsAlarmPirate(Boolean isAlarmPirate) {
    this.isAlarmPirate = isAlarmPirate;
  }


  @Column(name = "IS_ALARM_COLLISION")
  public Boolean getIsAlarmCollision() {
    return this.isAlarmCollision;
  }

  public void setIsAlarmCollision(Boolean isAlarmCollision) {
    this.isAlarmCollision = isAlarmCollision;
  }


  @Column(name = "IS_ALARM_DAMAGE")
  public Boolean getIsAlarmDamage() {
    return this.isAlarmDamage;
  }

  public void setIsAlarmDamage(Boolean isAlarmDamage) {
    this.isAlarmDamage = isAlarmDamage;
  }


  @Column(name = "IS_ALARM_HEAVY_WEATHER_L4")
  public Boolean getIsAlarmHeavyWeatherL4() {
    return this.isAlarmHeavyWeatherL4;
  }

  public void setIsAlarmHeavyWeatherL4(Boolean isAlarmHeavyWeatherL4) {
    this.isAlarmHeavyWeatherL4 = isAlarmHeavyWeatherL4;
  }


  @Column(name = "IS_ALARM_HEAVY_WEATHER_L6")
  public Boolean getIsAlarmHeavyWeatherL6() {
    return this.isAlarmHeavyWeatherL6;
  }

  public void setIsAlarmHeavyWeatherL6(Boolean isAlarmHeavyWeatherL6) {
    this.isAlarmHeavyWeatherL6 = isAlarmHeavyWeatherL6;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


