package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCfgVesselParticular generated by hbm2java
 */
@Entity
@Table(name = "FSM_CFG_VESSEL_PARTICULAR", catalog = "UMDP")
public class FsmCfgVesselParticular implements java.io.Serializable {


  private String vesselNo;
  private String item;
  private String value;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCfgVesselParticular() {}


  public FsmCfgVesselParticular(String vesselNo) {
    this.vesselNo = vesselNo;
  }

  public FsmCfgVesselParticular(String vesselNo, String item, String value, String createUser,
      Date createDate, String updateUser, Date updateDate) {
    this.vesselNo = vesselNo;
    this.item = item;
    this.value = value;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "VESSEL_NO", unique = true, nullable = false, length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "ITEM", length = 100)
  public String getItem() {
    return this.item;
  }

  public void setItem(String item) {
    this.item = item;
  }


  @Column(name = "VALUE", length = 200)
  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


