package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FsmCurVesselApDetailId generated by hbm2java
 */
@Embeddable
public class FsmCurVesselApDetailId implements java.io.Serializable {


  private String vesselNo;
  private String apDetailCd;

  public FsmCurVesselApDetailId() {}

  public FsmCurVesselApDetailId(String vesselNo, String apDetailCd) {
    this.vesselNo = vesselNo;
    this.apDetailCd = apDetailCd;
  }



  @Column(name = "VESSEL_NO", nullable = false, length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "AP_DETAIL_CD", nullable = false, length = 100)
  public String getApDetailCd() {
    return this.apDetailCd;
  }

  public void setApDetailCd(String apDetailCd) {
    this.apDetailCd = apDetailCd;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof FsmCurVesselApDetailId))
      return false;
    FsmCurVesselApDetailId castOther = (FsmCurVesselApDetailId) other;

    return ((this.getVesselNo() == castOther.getVesselNo()) || (this.getVesselNo() != null
        && castOther.getVesselNo() != null && this.getVesselNo().equals(castOther.getVesselNo())))
        && ((this.getApDetailCd() == castOther.getApDetailCd())
            || (this.getApDetailCd() != null && castOther.getApDetailCd() != null
                && this.getApDetailCd().equals(castOther.getApDetailCd())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getVesselNo() == null ? 0 : this.getVesselNo().hashCode());
    result = 37 * result + (getApDetailCd() == null ? 0 : this.getApDetailCd().hashCode());
    return result;
  }


}


