package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurCaptainHabit generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_CAPTAIN_HABIT", catalog = "UMDP")
public class FsmCurCaptainHabit implements java.io.Serializable {


  private FsmCurCaptainHabitId id;
  private String value;
  private Long seq;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurCaptainHabit() {}


  public FsmCurCaptainHabit(FsmCurCaptainHabitId id) {
    this.id = id;
  }

  public FsmCurCaptainHabit(FsmCurCaptainHabitId id, String value, Long seq, String createUser,
      Date createDate, String updateUser, Date updateDate) {
    this.id = id;
    this.value = value;
    this.seq = seq;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @EmbeddedId


  @AttributeOverrides({
      @AttributeOverride(name = "vesselNo",
          column = @Column(name = "VESSEL_NO", nullable = false, length = 20)),
      @AttributeOverride(name = "item",
          column = @Column(name = "ITEM", nullable = false, length = 100))})
  public FsmCurCaptainHabitId getId() {
    return this.id;
  }

  public void setId(FsmCurCaptainHabitId id) {
    this.id = id;
  }


  @Column(name = "VALUE", length = 200)
  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Column(name = "SEQ")
  public Long getSeq() {
    return this.seq;
  }

  public void setSeq(Long seq) {
    this.seq = seq;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


