package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurVesselNmea generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_VESSEL_NMEA", catalog = "UMDP")
public class FsmCurVesselNmea implements java.io.Serializable {


  private long id;
  private String vesselNo;
  private String nmea;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurVesselNmea() {}


  public FsmCurVesselNmea(long id) {
    this.id = id;
  }

  public FsmCurVesselNmea(long id, String vesselNo, String nmea, String createUser, Date createDate,
      String updateUser, Date updateDate) {
    this.id = id;
    this.vesselNo = vesselNo;
    this.nmea = nmea;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }


  @Column(name = "VESSEL_NO", length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "NMEA", length = 1000)
  public String getNmea() {
    return this.nmea;
  }

  public void setNmea(String nmea) {
    this.nmea = nmea;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


