package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurVessel generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_VESSEL", catalog = "UMDP")
public class FsmCurVessel implements java.io.Serializable {


  private String no;
  private String callSign;
  private String imoNo;
  private String latitude;
  private String longitude;
  private String planCrs;
  private String hdg;
  private String cog;
  private String sog;
  private String stw;
  private String spd;
  private String dest;
  private String destNm;
  private Date eta;
  private Date lmt;
  private String depth;
  private String ttg;
  private String rudder;
  private String windDirR;
  private String windSpdR;
  private String flowDirR;
  private String flowSpdR;
  private String windDirT;
  private String windSpdT;
  private String flowDirT;
  private String flowSpdT;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurVessel() {}


  public FsmCurVessel(String no) {
    this.no = no;
  }

  public FsmCurVessel(String no, String callSign, String imoNo, String latitude, String longitude,
      String planCrs, String hdg, String cog, String sog, String stw, String spd, String dest,
      String destNm, Date eta, Date lmt, String depth, String ttg, String rudder, String windDirR,
      String windSpdR, String flowDirR, String flowSpdR, String windDirT, String windSpdT,
      String flowDirT, String flowSpdT, String createUser, Date createDate, String updateUser,
      Date updateDate) {
    this.no = no;
    this.callSign = callSign;
    this.imoNo = imoNo;
    this.latitude = latitude;
    this.longitude = longitude;
    this.planCrs = planCrs;
    this.hdg = hdg;
    this.cog = cog;
    this.sog = sog;
    this.stw = stw;
    this.spd = spd;
    this.dest = dest;
    this.destNm = destNm;
    this.eta = eta;
    this.lmt = lmt;
    this.depth = depth;
    this.ttg = ttg;
    this.rudder = rudder;
    this.windDirR = windDirR;
    this.windSpdR = windSpdR;
    this.flowDirR = flowDirR;
    this.flowSpdR = flowSpdR;
    this.windDirT = windDirT;
    this.windSpdT = windSpdT;
    this.flowDirT = flowDirT;
    this.flowSpdT = flowSpdT;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "NO", unique = true, nullable = false, length = 20)
  public String getNo() {
    return this.no;
  }

  public void setNo(String no) {
    this.no = no;
  }


  @Column(name = "CALL_SIGN", length = 20)
  public String getCallSign() {
    return this.callSign;
  }

  public void setCallSign(String callSign) {
    this.callSign = callSign;
  }


  @Column(name = "IMO_NO", length = 20)
  public String getImoNo() {
    return this.imoNo;
  }

  public void setImoNo(String imoNo) {
    this.imoNo = imoNo;
  }


  @Column(name = "LATITUDE", length = 20)
  public String getLatitude() {
    return this.latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  @Column(name = "LONGITUDE", length = 20)
  public String getLongitude() {
    return this.longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  @Column(name = "PLAN_CRS", length = 20)
  public String getPlanCrs() {
    return this.planCrs;
  }

  public void setPlanCrs(String planCrs) {
    this.planCrs = planCrs;
  }


  @Column(name = "HDG", length = 20)
  public String getHdg() {
    return this.hdg;
  }

  public void setHdg(String hdg) {
    this.hdg = hdg;
  }


  @Column(name = "COG", length = 20)
  public String getCog() {
    return this.cog;
  }

  public void setCog(String cog) {
    this.cog = cog;
  }


  @Column(name = "SOG", length = 20)
  public String getSog() {
    return this.sog;
  }

  public void setSog(String sog) {
    this.sog = sog;
  }


  @Column(name = "STW", length = 20)
  public String getStw() {
    return this.stw;
  }

  public void setStw(String stw) {
    this.stw = stw;
  }


  @Column(name = "SPD", length = 20)
  public String getSpd() {
    return this.spd;
  }

  public void setSpd(String spd) {
    this.spd = spd;
  }


  @Column(name = "DEST", length = 20)
  public String getDest() {
    return this.dest;
  }

  public void setDest(String dest) {
    this.dest = dest;
  }


  @Column(name = "DEST_NM", length = 20)
  public String getDestNm() {
    return this.destNm;
  }

  public void setDestNm(String destNm) {
    this.destNm = destNm;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "ETA", length = 26)
  public Date getEta() {
    return this.eta;
  }

  public void setEta(Date eta) {
    this.eta = eta;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "LMT", length = 26)
  public Date getLmt() {
    return this.lmt;
  }

  public void setLmt(Date lmt) {
    this.lmt = lmt;
  }


  @Column(name = "DEPTH", length = 20)
  public String getDepth() {
    return this.depth;
  }

  public void setDepth(String depth) {
    this.depth = depth;
  }


  @Column(name = "TTG", length = 20)
  public String getTtg() {
    return this.ttg;
  }

  public void setTtg(String ttg) {
    this.ttg = ttg;
  }


  @Column(name = "RUDDER", length = 20)
  public String getRudder() {
    return this.rudder;
  }

  public void setRudder(String rudder) {
    this.rudder = rudder;
  }


  @Column(name = "WIND_DIR_R", length = 20)
  public String getWindDirR() {
    return this.windDirR;
  }

  public void setWindDirR(String windDirR) {
    this.windDirR = windDirR;
  }


  @Column(name = "WIND_SPD_R", length = 20)
  public String getWindSpdR() {
    return this.windSpdR;
  }

  public void setWindSpdR(String windSpdR) {
    this.windSpdR = windSpdR;
  }


  @Column(name = "FLOW_DIR_R", length = 20)
  public String getFlowDirR() {
    return this.flowDirR;
  }

  public void setFlowDirR(String flowDirR) {
    this.flowDirR = flowDirR;
  }


  @Column(name = "FLOW_SPD_R", length = 20)
  public String getFlowSpdR() {
    return this.flowSpdR;
  }

  public void setFlowSpdR(String flowSpdR) {
    this.flowSpdR = flowSpdR;
  }


  @Column(name = "WIND_DIR_T", length = 20)
  public String getWindDirT() {
    return this.windDirT;
  }

  public void setWindDirT(String windDirT) {
    this.windDirT = windDirT;
  }


  @Column(name = "WIND_SPD_T", length = 20)
  public String getWindSpdT() {
    return this.windSpdT;
  }

  public void setWindSpdT(String windSpdT) {
    this.windSpdT = windSpdT;
  }


  @Column(name = "FLOW_DIR_T", length = 20)
  public String getFlowDirT() {
    return this.flowDirT;
  }

  public void setFlowDirT(String flowDirT) {
    this.flowDirT = flowDirT;
  }


  @Column(name = "FLOW_SPD_T", length = 20)
  public String getFlowSpdT() {
    return this.flowSpdT;
  }

  public void setFlowSpdT(String flowSpdT) {
    this.flowSpdT = flowSpdT;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


