package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurVesselAp generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_VESSEL_AP", catalog = "UMDP")
public class FsmCurVesselAp implements java.io.Serializable {


  private String vesselNo;
  private String haStatusCd;
  private String apStatus;
  private Long apVersion;
  private Date signalDate;
  private String deployStatusCd;
  private Date deployDate;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurVesselAp() {}


  public FsmCurVesselAp(String vesselNo) {
    this.vesselNo = vesselNo;
  }

  public FsmCurVesselAp(String vesselNo, String haStatusCd, String apStatus, Long apVersion,
      Date signalDate, String deployStatusCd, Date deployDate, String createUser, Date createDate,
      String updateUser, Date updateDate) {
    this.vesselNo = vesselNo;
    this.haStatusCd = haStatusCd;
    this.apStatus = apStatus;
    this.apVersion = apVersion;
    this.signalDate = signalDate;
    this.deployStatusCd = deployStatusCd;
    this.deployDate = deployDate;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "VESSEL_NO", unique = true, nullable = false, length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "HA_STATUS_CD", length = 100)
  public String getHaStatusCd() {
    return this.haStatusCd;
  }

  public void setHaStatusCd(String haStatusCd) {
    this.haStatusCd = haStatusCd;
  }


  @Column(name = "AP_STATUS", length = 200)
  public String getApStatus() {
    return this.apStatus;
  }

  public void setApStatus(String apStatus) {
    this.apStatus = apStatus;
  }


  @Column(name = "AP_VERSION")
  public Long getApVersion() {
    return this.apVersion;
  }

  public void setApVersion(Long apVersion) {
    this.apVersion = apVersion;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "SIGNAL_DATE", length = 26)
  public Date getSignalDate() {
    return this.signalDate;
  }

  public void setSignalDate(Date signalDate) {
    this.signalDate = signalDate;
  }


  @Column(name = "DEPLOY_STATUS_CD", length = 100)
  public String getDeployStatusCd() {
    return this.deployStatusCd;
  }

  public void setDeployStatusCd(String deployStatusCd) {
    this.deployStatusCd = deployStatusCd;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "DEPLOY_DATE", length = 26)
  public Date getDeployDate() {
    return this.deployDate;
  }

  public void setDeployDate(Date deployDate) {
    this.deployDate = deployDate;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


