package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurTtQRecv generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_TT_Q_RECV", catalog = "UMDP")
public class FsmCurTtQRecv implements java.io.Serializable {


  private String id;
  private String ttCateCd;
  private String ttEventCd;
  private String ownerId;
  private String ttStatusCd;
  private String ttOperCd;
  private Date genDate;
  private String genEmpId;
  private Date replyDate;
  private String replyEmpId;
  private Date apprDate;
  private String apprEmpId;
  private Date rjctDate;
  private String rjctEmpId;
  private String ttRcTypeCd;
  private String ttTtRcCd;
  private String cmt;
  private String vesselNo;
  private String latitude;
  private String longitude;
  private Long cpa;
  private Long tcpa;
  private String ctNo;
  private String ctName;
  private String ctLatitude;
  private String ctLongitude;
  private Long eqpId;
  private Date sendDate;
  private Date recvDate;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurTtQRecv() {}


  public FsmCurTtQRecv(String id) {
    this.id = id;
  }

  public FsmCurTtQRecv(String id, String ttCateCd, String ttEventCd, String ownerId,
      String ttStatusCd, String ttOperCd, Date genDate, String genEmpId, Date replyDate,
      String replyEmpId, Date apprDate, String apprEmpId, Date rjctDate, String rjctEmpId,
      String ttRcTypeCd, String ttTtRcCd, String cmt, String vesselNo, String latitude,
      String longitude, Long cpa, Long tcpa, String ctNo, String ctName, String ctLatitude,
      String ctLongitude, Long eqpId, Date sendDate, Date recvDate, String createUser,
      Date createDate, String updateUser, Date updateDate) {
    this.id = id;
    this.ttCateCd = ttCateCd;
    this.ttEventCd = ttEventCd;
    this.ownerId = ownerId;
    this.ttStatusCd = ttStatusCd;
    this.ttOperCd = ttOperCd;
    this.genDate = genDate;
    this.genEmpId = genEmpId;
    this.replyDate = replyDate;
    this.replyEmpId = replyEmpId;
    this.apprDate = apprDate;
    this.apprEmpId = apprEmpId;
    this.rjctDate = rjctDate;
    this.rjctEmpId = rjctEmpId;
    this.ttRcTypeCd = ttRcTypeCd;
    this.ttTtRcCd = ttTtRcCd;
    this.cmt = cmt;
    this.vesselNo = vesselNo;
    this.latitude = latitude;
    this.longitude = longitude;
    this.cpa = cpa;
    this.tcpa = tcpa;
    this.ctNo = ctNo;
    this.ctName = ctName;
    this.ctLatitude = ctLatitude;
    this.ctLongitude = ctLongitude;
    this.eqpId = eqpId;
    this.sendDate = sendDate;
    this.recvDate = recvDate;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false, length = 100)
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Column(name = "TT_CATE_CD", length = 100)
  public String getTtCateCd() {
    return this.ttCateCd;
  }

  public void setTtCateCd(String ttCateCd) {
    this.ttCateCd = ttCateCd;
  }


  @Column(name = "TT_EVENT_CD", length = 100)
  public String getTtEventCd() {
    return this.ttEventCd;
  }

  public void setTtEventCd(String ttEventCd) {
    this.ttEventCd = ttEventCd;
  }


  @Column(name = "OWNER_ID", length = 50)
  public String getOwnerId() {
    return this.ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  @Column(name = "TT_STATUS_CD", length = 100)
  public String getTtStatusCd() {
    return this.ttStatusCd;
  }

  public void setTtStatusCd(String ttStatusCd) {
    this.ttStatusCd = ttStatusCd;
  }


  @Column(name = "TT_OPER_CD", length = 100)
  public String getTtOperCd() {
    return this.ttOperCd;
  }

  public void setTtOperCd(String ttOperCd) {
    this.ttOperCd = ttOperCd;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "GEN_DATE", length = 26)
  public Date getGenDate() {
    return this.genDate;
  }

  public void setGenDate(Date genDate) {
    this.genDate = genDate;
  }


  @Column(name = "GEN_EMP_ID", length = 50)
  public String getGenEmpId() {
    return this.genEmpId;
  }

  public void setGenEmpId(String genEmpId) {
    this.genEmpId = genEmpId;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "REPLY_DATE", length = 26)
  public Date getReplyDate() {
    return this.replyDate;
  }

  public void setReplyDate(Date replyDate) {
    this.replyDate = replyDate;
  }


  @Column(name = "REPLY_EMP_ID", length = 50)
  public String getReplyEmpId() {
    return this.replyEmpId;
  }

  public void setReplyEmpId(String replyEmpId) {
    this.replyEmpId = replyEmpId;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "APPR_DATE", length = 26)
  public Date getApprDate() {
    return this.apprDate;
  }

  public void setApprDate(Date apprDate) {
    this.apprDate = apprDate;
  }


  @Column(name = "APPR_EMP_ID", length = 50)
  public String getApprEmpId() {
    return this.apprEmpId;
  }

  public void setApprEmpId(String apprEmpId) {
    this.apprEmpId = apprEmpId;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "RJCT_DATE", length = 26)
  public Date getRjctDate() {
    return this.rjctDate;
  }

  public void setRjctDate(Date rjctDate) {
    this.rjctDate = rjctDate;
  }


  @Column(name = "RJCT_EMP_ID", length = 50)
  public String getRjctEmpId() {
    return this.rjctEmpId;
  }

  public void setRjctEmpId(String rjctEmpId) {
    this.rjctEmpId = rjctEmpId;
  }


  @Column(name = "TT_RC_TYPE_CD", length = 100)
  public String getTtRcTypeCd() {
    return this.ttRcTypeCd;
  }

  public void setTtRcTypeCd(String ttRcTypeCd) {
    this.ttRcTypeCd = ttRcTypeCd;
  }


  @Column(name = "TT_TT_RC_CD", length = 100)
  public String getTtTtRcCd() {
    return this.ttTtRcCd;
  }

  public void setTtTtRcCd(String ttTtRcCd) {
    this.ttTtRcCd = ttTtRcCd;
  }


  @Column(name = "CMT", length = 1000)
  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }


  @Column(name = "VESSEL_NO", length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "LATITUDE", length = 20)
  public String getLatitude() {
    return this.latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  @Column(name = "LONGITUDE", length = 20)
  public String getLongitude() {
    return this.longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  @Column(name = "CPA")
  public Long getCpa() {
    return this.cpa;
  }

  public void setCpa(Long cpa) {
    this.cpa = cpa;
  }


  @Column(name = "TCPA")
  public Long getTcpa() {
    return this.tcpa;
  }

  public void setTcpa(Long tcpa) {
    this.tcpa = tcpa;
  }


  @Column(name = "CT_NO", length = 100)
  public String getCtNo() {
    return this.ctNo;
  }

  public void setCtNo(String ctNo) {
    this.ctNo = ctNo;
  }


  @Column(name = "CT_NAME", length = 200)
  public String getCtName() {
    return this.ctName;
  }

  public void setCtName(String ctName) {
    this.ctName = ctName;
  }


  @Column(name = "CT_LATITUDE", length = 20)
  public String getCtLatitude() {
    return this.ctLatitude;
  }

  public void setCtLatitude(String ctLatitude) {
    this.ctLatitude = ctLatitude;
  }


  @Column(name = "CT_LONGITUDE", length = 20)
  public String getCtLongitude() {
    return this.ctLongitude;
  }

  public void setCtLongitude(String ctLongitude) {
    this.ctLongitude = ctLongitude;
  }


  @Column(name = "EQP_ID")
  public Long getEqpId() {
    return this.eqpId;
  }

  public void setEqpId(Long eqpId) {
    this.eqpId = eqpId;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "SEND_DATE", length = 26)
  public Date getSendDate() {
    return this.sendDate;
  }

  public void setSendDate(Date sendDate) {
    this.sendDate = sendDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "RECV_DATE", length = 26)
  public Date getRecvDate() {
    return this.recvDate;
  }

  public void setRecvDate(Date recvDate) {
    this.recvDate = recvDate;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


