package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCurVesselNearby generated by hbm2java
 */
@Entity
@Table(name = "FSM_CUR_VESSEL_NEARBY", catalog = "UMDP")
public class FsmCurVesselNearby implements java.io.Serializable {


  private FsmCurVesselNearbyId id;
  private String name;
  private String callSign;
  private String imoNo;
  private String latitude;
  private String longitude;
  private String hdg;
  private String cog;
  private String sog;
  private String cpa;
  private String tcpa;
  private String status;
  private String shipType;
  private String length;
  private String width;
  private String dest;
  private Date eta;
  private String rot;
  private String dist;
  private String threatLevelCd;
  private Boolean isPirateP;
  private Boolean isDisplay;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCurVesselNearby() {}


  public FsmCurVesselNearby(FsmCurVesselNearbyId id) {
    this.id = id;
  }

  public FsmCurVesselNearby(FsmCurVesselNearbyId id, String name, String callSign, String imoNo,
      String latitude, String longitude, String hdg, String cog, String sog, String cpa,
      String tcpa, String status, String shipType, String length, String width, String dest,
      Date eta, String rot, String dist, String threatLevelCd, Boolean isPirateP, Boolean isDisplay,
      String createUser, Date createDate, String updateUser, Date updateDate) {
    this.id = id;
    this.name = name;
    this.callSign = callSign;
    this.imoNo = imoNo;
    this.latitude = latitude;
    this.longitude = longitude;
    this.hdg = hdg;
    this.cog = cog;
    this.sog = sog;
    this.cpa = cpa;
    this.tcpa = tcpa;
    this.status = status;
    this.shipType = shipType;
    this.length = length;
    this.width = width;
    this.dest = dest;
    this.eta = eta;
    this.rot = rot;
    this.dist = dist;
    this.threatLevelCd = threatLevelCd;
    this.isPirateP = isPirateP;
    this.isDisplay = isDisplay;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @EmbeddedId


  @AttributeOverrides({
      @AttributeOverride(name = "thisVesselNo",
          column = @Column(name = "THIS_VESSEL_NO", nullable = false, length = 20)),
      @AttributeOverride(name = "mmsi",
          column = @Column(name = "MMSI", nullable = false, length = 20))})
  public FsmCurVesselNearbyId getId() {
    return this.id;
  }

  public void setId(FsmCurVesselNearbyId id) {
    this.id = id;
  }


  @Column(name = "NAME", length = 20)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Column(name = "CALL_SIGN", length = 20)
  public String getCallSign() {
    return this.callSign;
  }

  public void setCallSign(String callSign) {
    this.callSign = callSign;
  }


  @Column(name = "IMO_NO", length = 20)
  public String getImoNo() {
    return this.imoNo;
  }

  public void setImoNo(String imoNo) {
    this.imoNo = imoNo;
  }


  @Column(name = "LATITUDE", length = 20)
  public String getLatitude() {
    return this.latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  @Column(name = "LONGITUDE", length = 20)
  public String getLongitude() {
    return this.longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  @Column(name = "HDG", length = 20)
  public String getHdg() {
    return this.hdg;
  }

  public void setHdg(String hdg) {
    this.hdg = hdg;
  }


  @Column(name = "COG", length = 20)
  public String getCog() {
    return this.cog;
  }

  public void setCog(String cog) {
    this.cog = cog;
  }


  @Column(name = "SOG", length = 20)
  public String getSog() {
    return this.sog;
  }

  public void setSog(String sog) {
    this.sog = sog;
  }


  @Column(name = "CPA", length = 20)
  public String getCpa() {
    return this.cpa;
  }

  public void setCpa(String cpa) {
    this.cpa = cpa;
  }


  @Column(name = "TCPA", length = 20)
  public String getTcpa() {
    return this.tcpa;
  }

  public void setTcpa(String tcpa) {
    this.tcpa = tcpa;
  }


  @Column(name = "STATUS", length = 20)
  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Column(name = "SHIP_TYPE", length = 20)
  public String getShipType() {
    return this.shipType;
  }

  public void setShipType(String shipType) {
    this.shipType = shipType;
  }


  @Column(name = "LENGTH", length = 20)
  public String getLength() {
    return this.length;
  }

  public void setLength(String length) {
    this.length = length;
  }


  @Column(name = "WIDTH", length = 20)
  public String getWidth() {
    return this.width;
  }

  public void setWidth(String width) {
    this.width = width;
  }


  @Column(name = "DEST", length = 20)
  public String getDest() {
    return this.dest;
  }

  public void setDest(String dest) {
    this.dest = dest;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "ETA", length = 26)
  public Date getEta() {
    return this.eta;
  }

  public void setEta(Date eta) {
    this.eta = eta;
  }


  @Column(name = "ROT", length = 20)
  public String getRot() {
    return this.rot;
  }

  public void setRot(String rot) {
    this.rot = rot;
  }


  @Column(name = "DIST", length = 20)
  public String getDist() {
    return this.dist;
  }

  public void setDist(String dist) {
    this.dist = dist;
  }


  @Column(name = "THREAT_LEVEL_CD", length = 100)
  public String getThreatLevelCd() {
    return this.threatLevelCd;
  }

  public void setThreatLevelCd(String threatLevelCd) {
    this.threatLevelCd = threatLevelCd;
  }


  @Column(name = "IS_PIRATE_P")
  public Boolean getIsPirateP() {
    return this.isPirateP;
  }

  public void setIsPirateP(Boolean isPirateP) {
    this.isPirateP = isPirateP;
  }


  @Column(name = "IS_DISPLAY")
  public Boolean getIsDisplay() {
    return this.isDisplay;
  }

  public void setIsDisplay(Boolean isDisplay) {
    this.isDisplay = isDisplay;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


