package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FsmCurCaptainHabitId generated by hbm2java
 */
@Embeddable
public class FsmCurCaptainHabitId implements java.io.Serializable {


  private String vesselNo;
  private String item;

  public FsmCurCaptainHabitId() {}

  public FsmCurCaptainHabitId(String vesselNo, String item) {
    this.vesselNo = vesselNo;
    this.item = item;
  }



  @Column(name = "VESSEL_NO", nullable = false, length = 20)
  public String getVesselNo() {
    return this.vesselNo;
  }

  public void setVesselNo(String vesselNo) {
    this.vesselNo = vesselNo;
  }


  @Column(name = "ITEM", nullable = false, length = 100)
  public String getItem() {
    return this.item;
  }

  public void setItem(String item) {
    this.item = item;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof FsmCurCaptainHabitId))
      return false;
    FsmCurCaptainHabitId castOther = (FsmCurCaptainHabitId) other;

    return ((this.getVesselNo() == castOther.getVesselNo()) || (this.getVesselNo() != null
        && castOther.getVesselNo() != null && this.getVesselNo().equals(castOther.getVesselNo())))
        && ((this.getItem() == castOther.getItem()) || (this.getItem() != null
            && castOther.getItem() != null && this.getItem().equals(castOther.getItem())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getVesselNo() == null ? 0 : this.getVesselNo().hashCode());
    result = 37 * result + (getItem() == null ? 0 : this.getItem().hashCode());
    return result;
  }


}


