package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCfgModelEqp generated by hbm2java
 */
@Entity
@Table(name = "FSM_CFG_MODEL_EQP", catalog = "UMDP")
public class FsmCfgModelEqp implements java.io.Serializable {


  private long id;
  private String area;
  private String post;
  private Long diagramId;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCfgModelEqp() {}


  public FsmCfgModelEqp(long id) {
    this.id = id;
  }

  public FsmCfgModelEqp(long id, String area, String post, Long diagramId, String createUser,
      Date createDate, String updateUser, Date updateDate) {
    this.id = id;
    this.area = area;
    this.post = post;
    this.diagramId = diagramId;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "ID", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }


  @Column(name = "AREA", length = 100)
  public String getArea() {
    return this.area;
  }

  public void setArea(String area) {
    this.area = area;
  }


  @Column(name = "POST", length = 100)
  public String getPost() {
    return this.post;
  }

  public void setPost(String post) {
    this.post = post;
  }


  @Column(name = "DIAGRAM_ID")
  public Long getDiagramId() {
    return this.diagramId;
  }

  public void setDiagramId(Long diagramId) {
    this.diagramId = diagramId;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


