package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmCfgModel generated by hbm2java
 */
@Entity
@Table(name = "FSM_CFG_MODEL", catalog = "UMDP")
public class FsmCfgModel implements java.io.Serializable {


  private long no;
  private String name;
  private Long diagramCnt;
  private String createUser;
  private Date createDate;
  private String updateUser;
  private Date updateDate;

  public FsmCfgModel() {}


  public FsmCfgModel(long no) {
    this.no = no;
  }

  public FsmCfgModel(long no, String name, Long diagramCnt, String createUser, Date createDate,
      String updateUser, Date updateDate) {
    this.no = no;
    this.name = name;
    this.diagramCnt = diagramCnt;
    this.createUser = createUser;
    this.createDate = createDate;
    this.updateUser = updateUser;
    this.updateDate = updateDate;
  }

  @Id


  @Column(name = "NO", unique = true, nullable = false)
  public long getNo() {
    return this.no;
  }

  public void setNo(long no) {
    this.no = no;
  }


  @Column(name = "NAME", length = 200)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Column(name = "DIAGRAM_CNT")
  public Long getDiagramCnt() {
    return this.diagramCnt;
  }

  public void setDiagramCnt(Long diagramCnt) {
    this.diagramCnt = diagramCnt;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }


  @Column(name = "UPDATE_USER", length = 50)
  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATE", length = 26)
  public Date getUpdateDate() {
    return this.updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }



}


