package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FsmMapPirateIncidentTypeId generated by hbm2java
 */
@Embeddable
public class FsmMapPirateIncidentTypeId implements java.io.Serializable {


  private long piId;
  private String piTypeCd;

  public FsmMapPirateIncidentTypeId() {}

  public FsmMapPirateIncidentTypeId(long piId, String piTypeCd) {
    this.piId = piId;
    this.piTypeCd = piTypeCd;
  }



  @Column(name = "PI_ID", nullable = false)
  public long getPiId() {
    return this.piId;
  }

  public void setPiId(long piId) {
    this.piId = piId;
  }


  @Column(name = "PI_TYPE_CD", nullable = false, length = 100)
  public String getPiTypeCd() {
    return this.piTypeCd;
  }

  public void setPiTypeCd(String piTypeCd) {
    this.piTypeCd = piTypeCd;
  }


  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof FsmMapPirateIncidentTypeId))
      return false;
    FsmMapPirateIncidentTypeId castOther = (FsmMapPirateIncidentTypeId) other;

    return (this.getPiId() == castOther.getPiId())
        && ((this.getPiTypeCd() == castOther.getPiTypeCd())
            || (this.getPiTypeCd() != null && castOther.getPiTypeCd() != null
                && this.getPiTypeCd().equals(castOther.getPiTypeCd())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (int) this.getPiId();
    result = 37 * result + (getPiTypeCd() == null ? 0 : this.getPiTypeCd().hashCode());
    return result;
  }


}


