package com.uming.fsm.bean;
// Generated 2017/8/2  11:34:49 by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FsmMapPirateIncidentType generated by hbm2java
 */
@Entity
@Table(name = "FSM_MAP_PIRATE_INCIDENT_TYPE", catalog = "UMDP")
public class FsmMapPirateIncidentType implements java.io.Serializable {


  private FsmMapPirateIncidentTypeId id;
  private String createUser;
  private Date createDate;

  public FsmMapPirateIncidentType() {}


  public FsmMapPirateIncidentType(FsmMapPirateIncidentTypeId id) {
    this.id = id;
  }

  public FsmMapPirateIncidentType(FsmMapPirateIncidentTypeId id, String createUser,
      Date createDate) {
    this.id = id;
    this.createUser = createUser;
    this.createDate = createDate;
  }

  @EmbeddedId


  @AttributeOverrides({
      @AttributeOverride(name = "piId", column = @Column(name = "PI_ID", nullable = false)),
      @AttributeOverride(name = "piTypeCd",
          column = @Column(name = "PI_TYPE_CD", nullable = false, length = 100))})
  public FsmMapPirateIncidentTypeId getId() {
    return this.id;
  }

  public void setId(FsmMapPirateIncidentTypeId id) {
    this.id = id;
  }


  @Column(name = "CREATE_USER", length = 50)
  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATE", length = 26)
  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }



}


